version: "3.4"
services:
  db:
    image: mysql:5.7
    container_name: my-mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./mysqlData/mysql:/var/lib/mysql     
    restart: always
volumes:
  mysqlData: